import * as fs from 'fs';
import * as path from 'path';

// Function to recursively scan directories and collect file paths
function scanDirectory(directory: string, dirName: string, basePath: string = '') {
    const result: Array<{ alias: string, src: string }> = [];
    const items = fs.readdirSync(directory);

    for (const item of items) {
        const itemPath = path.join(directory, item);
        const stats = fs.statSync(itemPath);
        if (itemPath.endsWith('.css')) continue;

        if (stats.isDirectory()) {
            // If it's a directory, recursively scan it
            const nestedResults = scanDirectory(
                itemPath,
                dirName,
                path.join(basePath, item)
            );

            // Merge nested results into our result object
            result.push(...nestedResults);
        } else {
            // If it's a file, add it to our results
            // Create the key by removing file extension and replacing any path separators with hyphens
            const relativePath = path.join(basePath, item);
            const key = relativePath
                .replace(/\.[^/.]+$/, '') // Remove file extension
                .split(path.sep)
                .join('-');

            // Store the path with forward slashes for consistency
            result.push({
                alias: key,
                src: './' + dirName + '/' + relativePath.split(path.sep).join('/')
            });
        }
    }
    return result;
}

// Function to generate TypeScript content
function generateTsContent(name: string, assets: Array<{ alias: string, src: string }>): string {
    const assetsString = assets.map(asset => 
        `    {\n      alias: "${asset.alias}",\n      src: "${asset.src}"\n    }`
    ).join(',\n');

    return `// Auto-generated bundle file
// Do not edit manually - this file is generated by the bundle generator

const ${name} = {
  name: "${name}",
  assets: [
${assetsString}
  ]
} as const;

export default ${name};

// Type helpers for intellisense
export type ${name.charAt(0).toUpperCase() + name.slice(1)}Aliases = typeof ${name}['assets'][number]['alias'];
export type ${name.charAt(0).toUpperCase() + name.slice(1)}Asset = typeof ${name}['assets'][number];
`;
}

// Main function - now generates TypeScript
function generateBundleTs(directory: string, name: string) {
    const dir = "public/" + directory;
    // Check if public directory exists
    if (!fs.existsSync(dir)) {
        console.error('Error: '+directory+' directory not found');
        process.exit(1);
    }

    // Scan the directory
    console.log(`Scanning ${directory}`);
    const assets = scanDirectory(dir, directory);

    // Ensure src directory exists
    const srcDir = path.resolve('src');
    if (!fs.existsSync(srcDir)) {
        fs.mkdirSync(srcDir, { recursive: true });
    }

    // Generate TypeScript content
    const tsContent = generateTsContent(name, assets);

    // Write the TypeScript file
    const outputPath = path.join(srcDir, name + '.ts');
    fs.writeFileSync(outputPath, tsContent);

    console.log(`Successfully generated ${outputPath}`);
    console.log(`Found ${assets.length} files`);
}

function generateBundles() {
    generateBundleTs('img', 'bundle');
    generateBundleTs('audio', 'bundle_sound');
}

// Run the function
generateBundles();