// Auto-generated bundle file
// Do not edit manually - this file is generated by the bundle generator

const bundle = {
  name: "bundle",
  assets: [
    {
      alias: "flare",
      src: "./img/flare.png"
    },
    {
      alias: "light",
      src: "./img/light.png"
    },
    {
      alias: "spirit",
      src: "./img/spirit.png"
    },
    {
      alias: "stone_1",
      src: "./img/stone_1.png"
    },
    {
      alias: "stone_2",
      src: "./img/stone_2.png"
    }
  ]
} as const;

export default bundle;

// Type helpers for intellisense
export type BundleAliases = typeof bundle['assets'][number]['alias'];
export type BundleAsset = typeof bundle['assets'][number];
