// Auto-generated bundle file
// Do not edit manually - this file is generated by the bundle generator

const bundle = {
  name: "bundle",
  assets: [
    {
      alias: "astronaut",
      src: "./img/astronaut.png"
    },
    {
      alias: "blurcircle",
      src: "./img/blurcircle.png"
    },
    {
      alias: "circle",
      src: "./img/circle.png"
    },
    {
      alias: "drill",
      src: "./img/drill.png"
    },
    {
      alias: "drillbit",
      src: "./img/drillbit.png"
    },
    {
      alias: "flare",
      src: "./img/flare.png"
    },
    {
      alias: "floodlight",
      src: "./img/floodlight.png"
    },
    {
      alias: "girder",
      src: "./img/girder.png"
    },
    {
      alias: "icon-Icon_Cross",
      src: "./img/icon/Icon_Cross.png"
    },
    {
      alias: "icon-Icon_Share1",
      src: "./img/icon/Icon_Share1.png"
    },
    {
      alias: "icon-Icon_Star",
      src: "./img/icon/Icon_Star.png"
    },
    {
      alias: "icon-Icon_Warning",
      src: "./img/icon/Icon_Warning.png"
    },
    {
      alias: "light",
      src: "./img/light.png"
    },
    {
      alias: "muzzle-Muzzle_01",
      src: "./img/muzzle/Muzzle_01.png"
    },
    {
      alias: "muzzle-Muzzle_02",
      src: "./img/muzzle/Muzzle_02.png"
    },
    {
      alias: "muzzle-Muzzle_03",
      src: "./img/muzzle/Muzzle_03.png"
    },
    {
      alias: "muzzle-Muzzle_04",
      src: "./img/muzzle/Muzzle_04.png"
    },
    {
      alias: "muzzle-Muzzle_05",
      src: "./img/muzzle/Muzzle_05.png"
    },
    {
      alias: "noisy-sqare",
      src: "./img/noisy-sqare.png"
    },
    {
      alias: "projectile",
      src: "./img/projectile.png"
    },
    {
      alias: "ritual",
      src: "./img/ritual.png"
    },
    {
      alias: "ship",
      src: "./img/ship.png"
    },
    {
      alias: "spirit",
      src: "./img/spirit.png"
    },
    {
      alias: "spotlight",
      src: "./img/spotlight.png"
    },
    {
      alias: "sqare",
      src: "./img/sqare.png"
    },
    {
      alias: "stone_1",
      src: "./img/stone_1.png"
    },
    {
      alias: "stone_2",
      src: "./img/stone_2.png"
    },
    {
      alias: "turret",
      src: "./img/turret.png"
    }
  ]
} as const;

export default bundle;

// Type helpers for intellisense
export type BundleAliases = typeof bundle['assets'][number]['alias'];
export type BundleAsset = typeof bundle['assets'][number];
