// Auto-generated bundle file
// Do not edit manually - this file is generated by the bundle generator

const bundle_sound = {
  name: "bundle_sound",
  assets: [

  ]
} as const;

export default bundle_sound;

// Type helpers for intellisense
export type Bundle_soundAliases = typeof bundle_sound['assets'][number]['alias'];
export type Bundle_soundAsset = typeof bundle_sound['assets'][number];
